# Generated by Django 5.0.6 on 2024-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_status",
            field=models.BooleanField(default=False),
        ),
    ]
